name: portfolio
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  provider: ^6.1.2
  http: ^1.2.2
  dio: ^5.7.0
  get_it: ^8.0.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  logger: ^2.5.0
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.8
  line_icons: ^2.0.3
  url_launcher: ^6.3.1
  timelines_plus: ^1.0.8
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - fonts/
  fonts:
    - family: NanumPenScript
      fonts:
        - asset: fonts/NanumPenScript-Regular.ttf
    - family: NotoSansKR
      fonts:
        - asset: fonts/NotoSansKR-Thin.otf
        - asset: fonts/NotoSansKR-Light.otf
        - asset: fonts/NotoSansKR-Regular.otf
        - asset: fonts/NotoSansKR-Medium.otf
        - asset: fonts/NotoSansKR-Bold.otf
        - asset: fonts/NotoSansKR-Black.otf
